CREATE TABLE J_AMORT_PAGO_PAR ( 
	CLAVE_PARTE_ID varchar(50) NOT NULL,
	AMORT_PAGO_ID bigint NOT NULL,
	FECHA_REL timestamp NOT NULL,
	DATA text
)
;

CREATE TABLE J_AMORTIZA_PAGOS ( 
	ID bigint NOT NULL,
	FECHA_PAGO timestamp NOT NULL,
	NO_PAGO integer,
	SALDO_INSOLUTO decimal(12,4),
	CAPITAL decimal(12,4),
	INTERES decimal(12,4),
	IMP_INTERES decimal(12,4),
	PORC_INTERES decimal(10,2),
	SEGURO decimal(12,4),
	IMP_SEGURO decimal(12,4),
	PORC_SEGURO decimal(10,2),
	COMISION decimal(12,4),
	IMP_COMISION decimal(12,4),
	PORC_COMISION decimal(10,2),
	TOTAL_PAGO decimal(12,4),
	CUENTA_FINAN_ID bigint NOT NULL
)
;

CREATE TABLE J_APLICA_IDIOMA ( 
	APLICACION_ID bigint NOT NULL,
	IDIOMA_ID bigint NOT NULL
)
;

CREATE TABLE J_APLICACIONES ( 
	ID bigint NOT NULL,
	NOMBRE_TECNICO varchar(150) NOT NULL,
	NOMBRE_LOGICO varchar(150),
	DESCRIPCION varchar(255),
	NOMBRE_VISIBLE varchar(100) NOT NULL,
	DATA text
)
;

CREATE TABLE J_CLI_DIRECC ( 
	CLI_ID bigint NOT NULL,
	DIRECC_ID bigint NOT NULL,
	ID bigint NOT NULL,
	TYPE_DIRECC_LIST varchar(50) NOT NULL,
	FECHA_REL timestamp,
	DATA text
)
;

CREATE TABLE J_CLI_MONE_ACTIVOS ( 
	CLIENTE_ID bigint NOT NULL,
	MONEDA_ID bigint NOT NULL,
	FECHA_REL timestamp NOT NULL,
	DATA text
)
;

CREATE TABLE J_CLI_PAR ( 
	CLAVE_PARTE_ID varchar(50) NOT NULL,
	CLIENTE_ID bigint NOT NULL,
	FECHA_REL timestamp NOT NULL,
	DATA text
)
;

CREATE TABLE J_CLI_PROD ( 
	ORG_ID bigint NOT NULL,
	PROD_ID bigint NOT NULL,
	TYPE_ENTIDAD_ID varchar(50) NOT NULL,
	FECHA_REL timestamp NOT NULL,
	DATA bigint
)
;

CREATE TABLE J_CLIENTE_REL ( 
	CLIENTE_ID bigint NOT NULL,
	CLIENTE_REL_ID bigint NOT NULL,
	TYPE_REL_LISTA varchar(50) NOT NULL,
	TYPE_ENTIDAD_ID varchar(50) NOT NULL,
	FECHA_REL timestamp,
	DATA text
)
;

CREATE TABLE J_CLIENTES ( 
	ID bigint NOT NULL,
	PRIMER_NOMBRE varchar(250) NOT NULL,
	SEGUNDO_NOMBRE varchar(100),
	TERCER_NOMBRE varchar(100) NOT NULL,
	CUARTO_NOMBRE varchar(100),
	PAR_ROWID bigint,
	PUESTO_OWNER_ID bigint NOT NULL,
	ORG_OWNER_ID bigint NOT NULL,
	USUARIO_CREO_ID bigint NOT NULL,
	USUARIO_MODIFICO_ID bigint NOT NULL,
	FECHA_CREO_REGISTRO timestamp NOT NULL,
	FECHA_MODIFICO_REGISTRO timestamp NOT NULL,
	DIVISA_ID_PR bigint NOT NULL,
	CLAVE_FISCAL varchar(50) NOT NULL,
	TYPE_LISTA varchar(50),
	DATA text,
	ORGANIZACION_FLG boolean DEFAULT 0 NOT NULL,
	CLAVE varchar(30) NOT NULL,
	TYPE_ENTIDAD_LISTA varchar(50) NOT NULL,
	TYPE_PERSONALIDAD_LISTA varchar(50) NOT NULL,
	PUESTO_ID_PR bigint,
	ORG_ID_PR bigint,
	DIRECC_ID bigint,
	USU_OWNER_ID bigint NOT NULL
)
;

CREATE TABLE J_CP_COLONIAS ( 
	ID bigint NOT NULL,
	TYPE_LIST varchar(50) NOT NULL,
	CODIGO_POSTAL varchar(5) NOT NULL,
	COLONIA varchar(200) NOT NULL,
	LOCALIDAD_POBLACION varchar(200),
	CIUDAD_MUNICIPO varchar(200) NOT NULL,
	ENTIDAD_FEDERATIVA varchar(200) NOT NULL,
	PAIS varchar(200) NOT NULL,
	DATA text
)
;

CREATE TABLE J_CUEN_FINAN_PAR ( 
	CLAVE_PARTE_ID varchar(50) NOT NULL,
	CUENTA_FINAN_ID bigint NOT NULL,
	FECHA_REL timestamp NOT NULL,
	DATA text
)
;

CREATE TABLE J_CUEN_FINAN_REL ( 
	ID bigint NOT NULL,
	CUEN_FINAN_PADRE_ID bigint NOT NULL,
	CUEN_FINAN_HIJA_ID bigint NOT NULL,
	MONTO_TXN_ORIGEN decimal(12,4),
	DIVISA_ORIGEN_ID bigint,
	DIVISA_DESTINO_ID bigint,
	FECHA_REL timestamp NOT NULL,
	TYPE_REL_LISTA varchar(50),
	TYPE_ENTIDAD_ID varchar(50) NOT NULL,
	DATA text,
	TIPO_CAMBIO decimal(12,4),
	MONTO_TXN_DESTINO decimal(12,4),
	CANT_TXN_ORIGEN decimal(10,2),
	CANT_TXN_DESTINO decimal(10,2),
	TOTAL_TXN_ORIGEN decimal(12,4),
	TOTAL_TXN_DESTINO decimal(12,4)
)
;

CREATE TABLE J_CUENTA_FINANCIERA ( 
	ID bigint NOT NULL,
	DESCRIPCION varchar(255),
	DATA text,
	FECHA_SOL timestamp,
	ESTATUS_SOLIC_LISTA varchar(50),
	CUENTA_FINAN_ID_PAR bigint,
	CLI_PPAL_ID bigint NOT NULL,
	CLI_SECUN_ID bigint,
	PROD_PPAL_ID bigint NOT NULL,
	PROD_SECUN_ID bigint,
	DIVISA_ID bigint,
	CANT decimal(10,2) DEFAULT 1 NOT NULL,
	MONTO_SOL decimal(12,4),
	MONTO_AUT decimal(12,4),
	MONTO_ENTREGA decimal(12,4),
	MONTO_TOTAL_ENTREGA decimal(12,4)
)
;

CREATE TABLE J_DIRECCIONES ( 
	ID bigint NOT NULL,
	CP_ID bigint,
	LLAVE_USUARIO varchar(255) NOT NULL,
	CALLE_AVENIDA varchar(150) NOT NULL,
	NUM_EXT varchar(50) NOT NULL,
	NUM_INT varchar(50),
	TYPE_LIST varchar(50) NOT NULL,
	CODIGO_POSTAL varchar(5) NOT NULL,
	COLONIA varchar(200) NOT NULL,
	LOCALIDAD_POBLACION varchar(200) NOT NULL,
	CIUDAD_MUNICIPO varchar(200) NOT NULL,
	ENTIDAD_FEDERATIVA varchar(200) NOT NULL,
	PAIS varchar(200) NOT NULL,
	DATA text
)
;

CREATE TABLE J_DIVISAS ( 
	ID bigint NOT NULL,
	CODIGO varchar(15) NOT NULL,
	NOMBRE varchar(50) NOT NULL,
	PAIS_EMISOR varchar(50),
	SIMBOLO varchar(15),
	TRIANGULACION_UME boolean DEFAULT 0 NOT NULL,
	ACTIVO boolean DEFAULT 1 NOT NULL,
	DATA text
)
;

CREATE TABLE J_EMPLEADO_USUARIO ( 
	ID bigint NOT NULL,
	NOMBRE varchar(100) NOT NULL,
	APELLIDOS varchar(100),
	TYPE varchar(50) NOT NULL,
	SUB_TIPO varchar(50) NOT NULL,
	PUESTO_ID_PR bigint NOT NULL,
	ORG_ID_PR bigint NOT NULL,
	LOGIN varchar(50),
	PASSWORD varchar(100),
	DATA text
)
;

CREATE TABLE J_IDIOMAS ( 
	ID bigint NOT NULL,
	CODIGO varchar(3) NOT NULL,
	DESCRIPCION varchar(50) NOT NULL
)
;

CREATE TABLE J_LISTA_VALORES ( 
	ID bigint NOT NULL,
	TYPE varchar(50) NOT NULL,
	VALOR_VISIBLE varchar(50) NOT NULL,
	CODI_NO_DEPEN_IDIOMA varchar(50) NOT NULL,
	IDIOMA_ID bigint NOT NULL,
	LIC_PRINCIPAL_ID bigint,
	ORDEN smallint,
	ACTIVO_BANDERA boolean DEFAULT 1 NOT NULL,
	TRADUCIR_BANDERA boolean DEFAULT 1 NOT NULL,
	MULTILENGUA_BANDERA boolean DEFAULT 1 NOT NULL,
	NIVEL_REPLICACION varchar(50) NOT NULL,
	DEFAULT_BANDERA boolean
)
;

CREATE TABLE J_PAGOS_TXN ( 
	ID bigint NOT NULL,
	TRANSACC_ID bigint NOT NULL,
	FECHA_PAGO timestamp,
	REFERENCIA varchar(50),
	BANCO_ENTIDAD varchar(150),
	NO_TXN varchar(50),
	DIVISA_ID bigint,
	MONTO decimal(12,4),
	ESTATUS_LISTA varchar(50),
	IDENTIFICADO_CHECK boolean DEFAULT N,
	APLICADO_CHECK boolean
)
;

CREATE TABLE J_PANTALLAS_MODULOS ( 
	ID bigint NOT NULL,
	TYPE varchar(50) NOT NULL,
	NOMBRE_TECNICO varchar(100) NOT NULL,
	NOMBRE_LOGICO varchar(100) NOT NULL,
	NOMBRE_VISIBLE varchar(100) NOT NULL,
	PAR_ROWID bigint,
	APLICACION_ID bigint NOT NULL
)
;

CREATE TABLE J_PARTE_CALEN_PAGOS ( 
	CLAVE_ID varchar(50) NOT NULL,
	NOMBRE_ENTIDAD varchar(150),
	ESTATUS_LISTA varchar(50) NOT NULL
)
;

CREATE TABLE J_PARTE_CLI ( 
	CLAVE_ID varchar(50) NOT NULL,
	NOMBRE_ENTIDAD varchar(150) NOT NULL,
	ESTATUS_BANDERA boolean DEFAULT 1 NOT NULL
)
;

CREATE TABLE J_PARTE_CLI_CUEN_FINAN ( 
	PARTE_CUEN_FINAN_ID varchar(50) NOT NULL,
	PARTE_CLI_ID varchar(50) NOT NULL,
	FECHA_REL timestamp NOT NULL,
	DATA text
)
;

CREATE TABLE J_PARTE_CUEN_FINAN ( 
	CLAVE_ID varchar(50) NOT NULL,
	NOMBRE_ENTIDAD varchar(150),
	ESTATUS_BANDERA boolean DEFAULT 1 NOT NULL
)
;

CREATE TABLE J_PARTE_PROD ( 
	CLAVE_ID varchar(50) NOT NULL,
	NOMBRE_ENTIDAD varchar(150) NOT NULL,
	ESTATUS boolean DEFAULT 1 NOT NULL
)
;

CREATE TABLE J_PARTE_PROD_CUEN_FINAN ( 
	PARTE_CUEN_FINAN_ID varchar(50) NOT NULL,
	PARTE_PROD_ID varchar(50) NOT NULL,
	FECHA_REL timestamp NOT NULL,
	DATA text
)
;

CREATE TABLE J_PARTE_TRANSACCION ( 
	CLAVE_ID varchar(50) NOT NULL,
	NOMBRE varchar(150),
	ESTATUS_LISTA varchar(50) NOT NULL
)
;

CREATE TABLE J_PROD_PAR ( 
	CLAVE_PARTE_ID varchar(50) NOT NULL,
	PROD_ID bigint NOT NULL,
	FECHA_REL timestamp NOT NULL,
	DATA text
)
;

CREATE TABLE J_PROD_REL ( 
	PROD_ID bigint NOT NULL,
	PROD_REL_ID bigint NOT NULL,
	TYPE_REL_LISTA varchar(50) NOT NULL,
	TYPE_ENTIDAD_ID varchar(50) NOT NULL,
	FECHA_REL timestamp NOT NULL,
	DATA text
)
;

CREATE TABLE J_PRODUCTOS ( 
	ID bigint NOT NULL,
	NOMBRE varchar(150) NOT NULL,
	LINEA_PRODUCTO_ID bigint NOT NULL,
	SUBLINEA_PRODCUTO_ID bigint NOT NULL,
	TYPE_LISTA varchar(50),
	DIVISA_ACTIVO_ID bigint NOT NULL
)
;

CREATE TABLE J_PUESTO_EMPLEADO ( 
	PUESTO_ID bigint NOT NULL,
	EMPUSU_ID bigint NOT NULL,
	TYPE varchar(50) NOT NULL,
	PR boolean NOT NULL
)
;

CREATE TABLE J_PUESTO_TRABAJO ( 
	ID bigint NOT NULL,
	NOMBRE varchar(250) NOT NULL,
	TYPE varchar(100) NOT NULL,
	PAR_ROWID bigint,
	ORG_ID bigint NOT NULL,
	DATA text
)
;

CREATE TABLE J_RESPON_ROLL ( 
	ID bigint NOT NULL,
	NOMBRE varchar(150) NOT NULL,
	ORG_OWNER_ID bigint NOT NULL,
	PUESTO_OWNER_ID bigint NOT NULL,
	USUARIO_CREO_ID bigint
)
;

CREATE TABLE J_RESPON_VISTA ( 
	RESPONSA_ID bigint NOT NULL,
	VISTA_ID bigint NOT NULL
)
;

CREATE TABLE J_TRANSAC_PARTE ( 
	CLAVE_PARTE_ID varchar(50) NOT NULL,
	TRANSACT_ID bigint NOT NULL,
	FECHA_REL timestamp NOT NULL,
	DATA text
)
;

CREATE TABLE J_TRANSACC_REL ( 
	ID bigint NOT NULL,
	TRANSACC_PAR_ID bigint NOT NULL,
	TRANSACC_HIJA_ID bigint NOT NULL,
	TYPE_REL_LISTA varchar(50),
	TYPE_ENTIDAD_ID varchar(50),
	FECHA_REL timestamp,
	DATA text
)
;

CREATE TABLE J_TRANSACCIONES ( 
	ID bigint NOT NULL,
	DESCRIPCION varchar(255),
	MONTO_TOTAL_TXN_ORIGEN decimal(12,4),
	MONTO_TOTAL_IMPUESTOS decimal(12,4),
	FECHA_TRANSACCION timestamp NOT NULL,
	CLI1_ID bigint,
	CLI2_ID bigint,
	PROD1_ID bigint,
	PROD2_ID bigint,
	CUENTA_FIN1_ID bigint,
	CUENTA_FIN2_ID bigint,
	TRASAC_PAR_ID bigint,
	ESTATUS_TRAN_LISTA varchar(50),
	DATA text,
	CANT_TXN_ORIGEN decimal(10,2),
	MONTO_TXN_ORIGEN decimal(12,4),
	TIPO_CAMBIO decimal(12,4),
	DIVISA_ORI_ID bigint,
	DIVISA_DES_ID bigint,
	CANT_TXN_DESTINO decimal(12,4),
	MONTO_TXN_DESTINO decimal(12,4),
	MONTO_TOTAL_TXN_DESTINO decimal(12,4)
)
;

CREATE TABLE J_USUARIOS_RESPON ( 
	USUARIO_ID bigint NOT NULL,
	RESPONSA_ID bigint NOT NULL
)
;

CREATE TABLE J_VISTAS ( 
	ID bigint NOT NULL,
	NOMBRE_TECNICO varchar(150) NOT NULL,
	NOMBRE_LOGICO varchar(150),
	TYPE varchar(50) NOT NULL,
	NOMBRE_VISIBLE varchar(100) NOT NULL,
	PAR_ROWID bigint,
	PANTALLA_MODULO_ID bigint NOT NULL,
	TIPO_VISIBILIDAD varchar(50),
	VALOR_CAMPO_SESION_VISIBILIDAD varchar(100),
	TABLA_BASE_VISIBILIDAD varchar(100),
	COLUMNA_BASE_VISIBILIDAD varchar(100)
)
;


ALTER TABLE J_CLI_DIRECC
	ADD CONSTRAINT UQ_J_CLI_DIRECC_ID UNIQUE (ID)
;
ALTER TABLE J_CLIENTES
	ADD CONSTRAINT UQ_J_CLIENTES_CLAVE UNIQUE (CLAVE)
;
ALTER TABLE J_DIRECCIONES
	ADD CONSTRAINT UQ_J_DIRECCIONES_LLAVE_USUARIO UNIQUE (LLAVE_USUARIO)
;
ALTER TABLE J_AMORT_PAGO_PAR ADD CONSTRAINT PK_J_AMORT_PAGO_PAR 
	PRIMARY KEY (CLAVE_PARTE_ID, AMORT_PAGO_ID)
;


ALTER TABLE J_AMORTIZA_PAGOS ADD CONSTRAINT PK_J_AMORTIZA_PAGOS 
	PRIMARY KEY (ID)
;


ALTER TABLE J_APLICA_IDIOMA ADD CONSTRAINT PK_J_APLICA_IDIOMA 
	PRIMARY KEY (APLICACION_ID, IDIOMA_ID)
;


ALTER TABLE J_APLICACIONES ADD CONSTRAINT PK_J_APLICACIONES 
	PRIMARY KEY (ID)
;


ALTER TABLE J_CLI_DIRECC ADD CONSTRAINT PK_J_CLI_DIRECC 
	PRIMARY KEY (CLI_ID, DIRECC_ID)
;


ALTER TABLE J_CLI_MONE_ACTIVOS ADD CONSTRAINT PK_J_CLI_MON 
	PRIMARY KEY (CLIENTE_ID, MONEDA_ID)
;


ALTER TABLE J_CLI_PAR ADD CONSTRAINT PK_J_CLI_PAR 
	PRIMARY KEY (CLAVE_PARTE_ID, CLIENTE_ID)
;


ALTER TABLE J_CLI_PROD ADD CONSTRAINT PK_J_PROD_ORG 
	PRIMARY KEY (PROD_ID, ORG_ID, TYPE_ENTIDAD_ID)
;


ALTER TABLE J_CLIENTE_REL ADD CONSTRAINT PK_J_CLIENTE_REL 
	PRIMARY KEY (CLIENTE_ID, CLIENTE_REL_ID, TYPE_REL_LISTA)
;


ALTER TABLE J_CLIENTES ADD CONSTRAINT PK_J_ORG_EXT 
	PRIMARY KEY (ID)
;


ALTER TABLE J_CP_COLONIAS ADD CONSTRAINT PK_J_CP_COLONIAS 
	PRIMARY KEY (ID)
;


ALTER TABLE J_CUEN_FINAN_PAR ADD CONSTRAINT PK_J_CUEN_FINAN_PAR 
	PRIMARY KEY (CLAVE_PARTE_ID, CUENTA_FINAN_ID)
;


ALTER TABLE J_CUEN_FINAN_REL ADD CONSTRAINT PK_J_CUEN_FINAN_REL 
	PRIMARY KEY (ID)
;


ALTER TABLE J_CUENTA_FINANCIERA ADD CONSTRAINT PK_J_CUENTA_FINANCIERA 
	PRIMARY KEY (ID)
;


ALTER TABLE J_DIRECCIONES ADD CONSTRAINT PK_J_DIRECCIONES 
	PRIMARY KEY (ID)
;


ALTER TABLE J_DIVISAS ADD CONSTRAINT PK_J_MONEDA 
	PRIMARY KEY (ID)
;


ALTER TABLE J_EMPLEADO_USUARIO ADD CONSTRAINT PK_J_EMPLEADO_USUARIO 
	PRIMARY KEY (ID)
;


ALTER TABLE J_IDIOMAS ADD CONSTRAINT PK_J_IDIOMAS 
	PRIMARY KEY (ID)
;


ALTER TABLE J_LISTA_VALORES ADD CONSTRAINT PK_J_LISTA_VALORES 
	PRIMARY KEY (ID)
;


ALTER TABLE J_PAGOS_TXN ADD CONSTRAINT PK_J_PAGOS_TXN 
	PRIMARY KEY (ID)
;


ALTER TABLE J_PANTALLAS_MODULOS ADD CONSTRAINT PK_J_PANTALLAS_MODULOS 
	PRIMARY KEY (ID)
;


ALTER TABLE J_PARTE_CALEN_PAGOS ADD CONSTRAINT PK_J_PARTE_CALEN_PAGOS 
	PRIMARY KEY (CLAVE_ID)
;


ALTER TABLE J_PARTE_CLI ADD CONSTRAINT PK_J_PARTE_CLI 
	PRIMARY KEY (CLAVE_ID)
;


ALTER TABLE J_PARTE_CUEN_FINAN ADD CONSTRAINT PK_J_PARTE_CUENTA 
	PRIMARY KEY (CLAVE_ID)
;


ALTER TABLE J_PARTE_PROD ADD CONSTRAINT PK_J_PARTE_PROD 
	PRIMARY KEY (CLAVE_ID)
;


ALTER TABLE J_PARTE_TRANSACCION ADD CONSTRAINT PK_J_PARTE_TRANSACCION 
	PRIMARY KEY (CLAVE_ID)
;


ALTER TABLE J_PROD_PAR ADD CONSTRAINT PK_J_PROD_PAR 
	PRIMARY KEY (CLAVE_PARTE_ID, PROD_ID)
;


ALTER TABLE J_PROD_REL ADD CONSTRAINT PK_J_PROD_REL 
	PRIMARY KEY (PROD_ID, PROD_REL_ID, TYPE_REL_LISTA)
;


ALTER TABLE J_PRODUCTOS ADD CONSTRAINT PK_J_PRODUCTOS 
	PRIMARY KEY (ID)
;


ALTER TABLE J_PUESTO_EMPLEADO ADD CONSTRAINT PK_J_PUESTO_EMPLEADO 
	PRIMARY KEY (PUESTO_ID, EMPUSU_ID)
;


ALTER TABLE J_PUESTO_TRABAJO ADD CONSTRAINT PK_J_PUESTO_TRABAJO 
	PRIMARY KEY (ID)
;


ALTER TABLE J_RESPON_ROLL ADD CONSTRAINT PK_RESPONSABILIDAS_ROLL 
	PRIMARY KEY (ID)
;


ALTER TABLE J_RESPON_VISTA ADD CONSTRAINT PK_J_RESPON_VISTA 
	PRIMARY KEY (RESPONSA_ID, VISTA_ID)
;


ALTER TABLE J_TRANSAC_PARTE ADD CONSTRAINT PK_J_TRANSAC_PARTE 
	PRIMARY KEY (CLAVE_PARTE_ID, TRANSACT_ID)
;


ALTER TABLE J_TRANSACC_REL ADD CONSTRAINT PK_J_TRANSACC_REL 
	PRIMARY KEY (ID)
;


ALTER TABLE J_TRANSACCIONES ADD CONSTRAINT PK_J_TRANSACCIONES 
	PRIMARY KEY (ID)
;


ALTER TABLE J_USUARIOS_RESPON ADD CONSTRAINT PK_J_USUARIOS_VISTAS 
	PRIMARY KEY (USUARIO_ID, RESPONSA_ID)
;


ALTER TABLE J_VISTAS ADD CONSTRAINT PK_J_VISTAS 
	PRIMARY KEY (ID)
;




ALTER TABLE J_AMORT_PAGO_PAR ADD CONSTRAINT FK_J_AMORT_PAGO_PAR_J_AMORTIZA_PAGOS 
	FOREIGN KEY (AMORT_PAGO_ID) REFERENCES J_AMORTIZA_PAGOS (ID)
;

ALTER TABLE J_AMORT_PAGO_PAR ADD CONSTRAINT FK_J_AMORT_PAGO_PAR_J_PARTE_CALEN_PAGOS 
	FOREIGN KEY (CLAVE_PARTE_ID) REFERENCES J_PARTE_CALEN_PAGOS (CLAVE_ID)
;

ALTER TABLE J_AMORTIZA_PAGOS ADD CONSTRAINT FK_J_AMORTIZA_PAGOS_J_CUENTA_FINANCIERA 
	FOREIGN KEY (CUENTA_FINAN_ID) REFERENCES J_CUENTA_FINANCIERA (ID)
;

ALTER TABLE J_APLICA_IDIOMA ADD CONSTRAINT FK_J_APLICA_IDIOMA_J_APLICACIONES 
	FOREIGN KEY (APLICACION_ID) REFERENCES J_APLICACIONES (ID)
;

ALTER TABLE J_APLICA_IDIOMA ADD CONSTRAINT FK_J_APLICA_IDIOMA_J_IDIOMAS 
	FOREIGN KEY (IDIOMA_ID) REFERENCES J_IDIOMAS (ID)
;

ALTER TABLE J_CLI_DIRECC ADD CONSTRAINT FK_J_CLI_DIRECC_J_CLIENTES 
	FOREIGN KEY (CLI_ID) REFERENCES J_CLIENTES (ID)
;

ALTER TABLE J_CLI_DIRECC ADD CONSTRAINT FK_J_CLI_DIRECC_J_DIRECCIONES 
	FOREIGN KEY (DIRECC_ID) REFERENCES J_DIRECCIONES (ID)
;

ALTER TABLE J_CLI_MONE_ACTIVOS ADD CONSTRAINT FK_J_CLI_MON_J_CLIENTES 
	FOREIGN KEY (CLIENTE_ID) REFERENCES J_CLIENTES (ID)
;

ALTER TABLE J_CLI_MONE_ACTIVOS ADD CONSTRAINT FK_J_CLI_MON_J_MONEDA 
	FOREIGN KEY (MONEDA_ID) REFERENCES J_DIVISAS (ID)
;

ALTER TABLE J_CLI_PAR ADD CONSTRAINT FK_J_CLI_PAR_J_CLIENTES 
	FOREIGN KEY (CLIENTE_ID) REFERENCES J_CLIENTES (ID)
;

ALTER TABLE J_CLI_PAR ADD CONSTRAINT FK_J_CLI_PAR_J_PARTE_CLI 
	FOREIGN KEY (CLAVE_PARTE_ID) REFERENCES J_PARTE_CLI (CLAVE_ID)
;

ALTER TABLE J_CLI_PROD ADD CONSTRAINT FK_J_PROD_ORG_J_CLIENTES 
	FOREIGN KEY (ORG_ID) REFERENCES J_CLIENTES (ID)
;

ALTER TABLE J_CLI_PROD ADD CONSTRAINT FK_J_PROD_ORG_J_PARTE_PROD 
	FOREIGN KEY (TYPE_ENTIDAD_ID) REFERENCES J_PARTE_PROD (CLAVE_ID)
;

ALTER TABLE J_CLI_PROD ADD CONSTRAINT FK_J_PROD_ORG_J_PRODUCTOS 
	FOREIGN KEY (PROD_ID) REFERENCES J_PRODUCTOS (ID)
;

ALTER TABLE J_CLIENTE_REL ADD CONSTRAINT FK_J_CLIENTE_REL_J_CLIENTES 
	FOREIGN KEY (CLIENTE_ID) REFERENCES J_CLIENTES (ID)
;

ALTER TABLE J_CLIENTE_REL ADD CONSTRAINT FK_J_CLIENTE_REL_J_CLIENTES 
	FOREIGN KEY (CLIENTE_REL_ID) REFERENCES J_CLIENTES (ID)
;

ALTER TABLE J_CLIENTE_REL ADD CONSTRAINT FK_J_CLIENTE_REL_J_PARTE_CLI 
	FOREIGN KEY (TYPE_ENTIDAD_ID) REFERENCES J_PARTE_CLI (CLAVE_ID)
;

ALTER TABLE J_CLIENTES ADD CONSTRAINT FK_J_CLIENTES_J_CLI_DIRECC 
	FOREIGN KEY (DIRECC_ID) REFERENCES J_CLI_DIRECC (ID)
;

ALTER TABLE J_CLIENTES ADD CONSTRAINT FK_J_CLIENTES_J_CLIENTES 
	FOREIGN KEY (ORG_ID_PR) REFERENCES J_CLIENTES (ID)
;

ALTER TABLE J_CLIENTES ADD CONSTRAINT FK_J_CLIENTES_J_DIVISAS 
	FOREIGN KEY (DIVISA_ID_PR) REFERENCES J_DIVISAS (ID)
;

ALTER TABLE J_CLIENTES ADD CONSTRAINT FK_J_CLIENTES_J_PUESTO_TRABAJO 
	FOREIGN KEY (PUESTO_ID_PR) REFERENCES J_PUESTO_TRABAJO (ID)
;

ALTER TABLE J_CLIENTES ADD CONSTRAINT FK_J_ORG_EXT_J_ORG_EXT 
	FOREIGN KEY (PAR_ROWID) REFERENCES J_CLIENTES (ID)
;

ALTER TABLE J_CUEN_FINAN_PAR ADD CONSTRAINT FK_J_CUEN_FINAN_PAR_J_CUENTA_FINANCIERA 
	FOREIGN KEY (CUENTA_FINAN_ID) REFERENCES J_CUENTA_FINANCIERA (ID)
;

ALTER TABLE J_CUEN_FINAN_PAR ADD CONSTRAINT FK_J_CUEN_FINAN_PAR_J_PARTE_CUEN_FINAN 
	FOREIGN KEY (CLAVE_PARTE_ID) REFERENCES J_PARTE_CUEN_FINAN (CLAVE_ID)
;

ALTER TABLE J_CUEN_FINAN_REL ADD CONSTRAINT FK_J_CUEN_FINAN_REL_J_CUENTA_FINANCIERA 
	FOREIGN KEY (CUEN_FINAN_PADRE_ID) REFERENCES J_CUENTA_FINANCIERA (ID)
;

ALTER TABLE J_CUEN_FINAN_REL ADD CONSTRAINT FK_J_CUEN_FINAN_REL_J_CUENTA_FINANCIERA 
	FOREIGN KEY (CUEN_FINAN_HIJA_ID) REFERENCES J_CUENTA_FINANCIERA (ID)
;

ALTER TABLE J_CUEN_FINAN_REL ADD CONSTRAINT FK_J_CUEN_FINAN_REL_J_DIVISAS 
	FOREIGN KEY (DIVISA_ORIGEN_ID) REFERENCES J_DIVISAS (ID)
;

ALTER TABLE J_CUEN_FINAN_REL ADD CONSTRAINT FK_J_CUEN_FINAN_REL_J_DIVISAS 
	FOREIGN KEY (DIVISA_DESTINO_ID) REFERENCES J_DIVISAS (ID)
;

ALTER TABLE J_CUEN_FINAN_REL ADD CONSTRAINT FK_J_CUEN_FINAN_REL_J_PARTE_CUEN_FINAN 
	FOREIGN KEY (TYPE_ENTIDAD_ID) REFERENCES J_PARTE_CUEN_FINAN (CLAVE_ID)
;

ALTER TABLE J_CUENTA_FINANCIERA ADD CONSTRAINT FK_J_CUENTA_FINANCIERA_J_CLIENTES 
	FOREIGN KEY (CLI_PPAL_ID) REFERENCES J_CLIENTES (ID)
;

ALTER TABLE J_CUENTA_FINANCIERA ADD CONSTRAINT FK_J_CUENTA_FINANCIERA_J_CLIENTES 
	FOREIGN KEY (CLI_SECUN_ID) REFERENCES J_CLIENTES (ID)
;

ALTER TABLE J_CUENTA_FINANCIERA ADD CONSTRAINT FK_J_CUENTA_FINANCIERA_J_CUENTA_FINANCIERA 
	FOREIGN KEY (CUENTA_FINAN_ID_PAR) REFERENCES J_CUENTA_FINANCIERA (ID)
;

ALTER TABLE J_CUENTA_FINANCIERA ADD CONSTRAINT FK_J_CUENTA_FINANCIERA_J_DIVISAS 
	FOREIGN KEY (DIVISA_ID) REFERENCES J_DIVISAS (ID)
;

ALTER TABLE J_CUENTA_FINANCIERA ADD CONSTRAINT FK_J_CUENTA_FINANCIERA_J_PRODUCTOS 
	FOREIGN KEY (PROD_PPAL_ID) REFERENCES J_PRODUCTOS (ID)
;

ALTER TABLE J_CUENTA_FINANCIERA ADD CONSTRAINT FK_J_CUENTA_FINANCIERA_J_PRODUCTOS 
	FOREIGN KEY (PROD_SECUN_ID) REFERENCES J_PRODUCTOS (ID)
;

ALTER TABLE J_DIRECCIONES ADD CONSTRAINT FK_J_DIRECCIONES_J_CP_COLONIAS 
	FOREIGN KEY (CP_ID) REFERENCES J_CP_COLONIAS (ID)
;

ALTER TABLE J_LISTA_VALORES ADD CONSTRAINT FK_J_LISTA_VALORES_J_IDIOMAS 
	FOREIGN KEY (IDIOMA_ID) REFERENCES J_IDIOMAS (ID)
;

ALTER TABLE J_PAGOS_TXN ADD CONSTRAINT FK_J_PAGOS_TXN_J_DIVISAS 
	FOREIGN KEY (DIVISA_ID) REFERENCES J_DIVISAS (ID)
;

ALTER TABLE J_PAGOS_TXN ADD CONSTRAINT FK_J_PAGOS_TXN_J_TRANSACCIONES 
	FOREIGN KEY (TRANSACC_ID) REFERENCES J_TRANSACCIONES (ID)
;

ALTER TABLE J_PANTALLAS_MODULOS ADD CONSTRAINT FK_J_PANTALLAS_MODULOS_J_APLICACIONES 
	FOREIGN KEY (APLICACION_ID) REFERENCES J_APLICACIONES (ID)
;

ALTER TABLE J_PANTALLAS_MODULOS ADD CONSTRAINT FK_J_PANTALLAS_MODULOS_J_PANTALLAS_MODULOS 
	FOREIGN KEY (PAR_ROWID) REFERENCES J_PANTALLAS_MODULOS (ID)
;

ALTER TABLE J_PARTE_CLI_CUEN_FINAN ADD CONSTRAINT FK_J_PARTE_CLI_CUEN_FINAN_J_PARTE_CLI 
	FOREIGN KEY (PARTE_CLI_ID) REFERENCES J_PARTE_CLI (CLAVE_ID)
;

ALTER TABLE J_PARTE_CLI_CUEN_FINAN ADD CONSTRAINT FK_J_PARTE_CLI_CUEN_FINAN_J_PARTE_CUEN_FINAN 
	FOREIGN KEY (PARTE_CUEN_FINAN_ID) REFERENCES J_PARTE_CUEN_FINAN (CLAVE_ID)
;

ALTER TABLE J_PARTE_PROD_CUEN_FINAN ADD CONSTRAINT FK_J_PARTE_PROD_CUEN_FINAN_J_PARTE_CUEN_FINAN 
	FOREIGN KEY (PARTE_CUEN_FINAN_ID) REFERENCES J_PARTE_CUEN_FINAN (CLAVE_ID)
;

ALTER TABLE J_PARTE_PROD_CUEN_FINAN ADD CONSTRAINT FK_J_PARTE_PROD_CUEN_FINAN_J_PARTE_PROD 
	FOREIGN KEY (PARTE_PROD_ID) REFERENCES J_PARTE_PROD (CLAVE_ID)
;

ALTER TABLE J_PROD_PAR ADD CONSTRAINT FK_J_PROD_PAR_J_PARTE_PROD 
	FOREIGN KEY (CLAVE_PARTE_ID) REFERENCES J_PARTE_PROD (CLAVE_ID)
;

ALTER TABLE J_PROD_PAR ADD CONSTRAINT FK_J_PROD_PAR_J_PRODUCTOS 
	FOREIGN KEY (PROD_ID) REFERENCES J_PRODUCTOS (ID)
;

ALTER TABLE J_PROD_REL ADD CONSTRAINT FK_J_PROD_REL_J_PARTE_PROD 
	FOREIGN KEY (TYPE_ENTIDAD_ID) REFERENCES J_PARTE_PROD (CLAVE_ID)
;

ALTER TABLE J_PROD_REL ADD CONSTRAINT FK_J_PROD_REL_J_PRODUCTOS 
	FOREIGN KEY (PROD_ID) REFERENCES J_PRODUCTOS (ID)
;

ALTER TABLE J_PROD_REL ADD CONSTRAINT FK_J_PROD_REL_J_PRODUCTOS 
	FOREIGN KEY (PROD_REL_ID) REFERENCES J_PRODUCTOS (ID)
;

ALTER TABLE J_PRODUCTOS ADD CONSTRAINT FK_J_PRODUCTOS_J_DIVISAS 
	FOREIGN KEY (DIVISA_ACTIVO_ID) REFERENCES J_DIVISAS (ID)
;

ALTER TABLE J_PUESTO_EMPLEADO ADD CONSTRAINT FK_J_PUESTO_EMPLEADO_J_CLIENTES 
	FOREIGN KEY (EMPUSU_ID) REFERENCES J_CLIENTES (ID)
;

ALTER TABLE J_PUESTO_EMPLEADO ADD CONSTRAINT FK_J_PUESTO_EMPLEADO_J_PUESTO_TRABAJO 
	FOREIGN KEY (PUESTO_ID) REFERENCES J_PUESTO_TRABAJO (ID)
;

ALTER TABLE J_PUESTO_TRABAJO ADD CONSTRAINT FK_J_PUESTO_TRABAJO_J_ORG_EXT 
	FOREIGN KEY (ORG_ID) REFERENCES J_CLIENTES (ID)
;

ALTER TABLE J_PUESTO_TRABAJO ADD CONSTRAINT FK_J_PUESTO_TRABAJO_J_PUESTO_TRABAJO 
	FOREIGN KEY (PAR_ROWID) REFERENCES J_PUESTO_TRABAJO (ID)
;

ALTER TABLE J_RESPON_VISTA ADD CONSTRAINT FK_J_RESPON_VISTA_J_RESPON_ROLL 
	FOREIGN KEY (RESPONSA_ID) REFERENCES J_RESPON_ROLL (ID)
;

ALTER TABLE J_RESPON_VISTA ADD CONSTRAINT FK_J_RESPON_VISTA_J_VISTAS 
	FOREIGN KEY (VISTA_ID) REFERENCES J_VISTAS (ID)
;

ALTER TABLE J_TRANSAC_PARTE ADD CONSTRAINT FK_J_TRANSAC_PARTE_J_PARTE_TRANSACCION 
	FOREIGN KEY (CLAVE_PARTE_ID) REFERENCES J_PARTE_TRANSACCION (CLAVE_ID)
;

ALTER TABLE J_TRANSAC_PARTE ADD CONSTRAINT FK_J_TRANSAC_PARTE_J_TRANSACCIONES 
	FOREIGN KEY (TRANSACT_ID) REFERENCES J_TRANSACCIONES (ID)
;

ALTER TABLE J_TRANSACC_REL ADD CONSTRAINT FK_J_TRANSACC_REL_J_PARTE_TRANSACCION 
	FOREIGN KEY (TYPE_ENTIDAD_ID) REFERENCES J_PARTE_TRANSACCION (CLAVE_ID)
;

ALTER TABLE J_TRANSACC_REL ADD CONSTRAINT FK_J_TRANSACC_REL_J_TRANSACCIONES 
	FOREIGN KEY (TRANSACC_PAR_ID) REFERENCES J_TRANSACCIONES (ID)
;

ALTER TABLE J_TRANSACC_REL ADD CONSTRAINT FK_J_TRANSACC_REL_J_TRANSACCIONES 
	FOREIGN KEY (TRANSACC_HIJA_ID) REFERENCES J_TRANSACCIONES (ID)
;

ALTER TABLE J_TRANSACCIONES ADD CONSTRAINT FK_J_TRANSACCIONES_J_CLIENTES 
	FOREIGN KEY (CLI1_ID) REFERENCES J_CLIENTES (ID)
;

ALTER TABLE J_TRANSACCIONES ADD CONSTRAINT FK_J_TRANSACCIONES_J_CLIENTES 
	FOREIGN KEY (CLI2_ID) REFERENCES J_CLIENTES (ID)
;

ALTER TABLE J_TRANSACCIONES ADD CONSTRAINT FK_J_TRANSACCIONES_J_CUENTA_FINANCIERA 
	FOREIGN KEY (CUENTA_FIN1_ID) REFERENCES J_CUENTA_FINANCIERA (ID)
;

ALTER TABLE J_TRANSACCIONES ADD CONSTRAINT FK_J_TRANSACCIONES_J_CUENTA_FINANCIERA 
	FOREIGN KEY (CUENTA_FIN2_ID) REFERENCES J_CUENTA_FINANCIERA (ID)
;

ALTER TABLE J_TRANSACCIONES ADD CONSTRAINT FK_J_TRANSACCIONES_J_DIVISAS 
	FOREIGN KEY (DIVISA_ORI_ID) REFERENCES J_DIVISAS (ID)
;

ALTER TABLE J_TRANSACCIONES ADD CONSTRAINT FK_J_TRANSACCIONES_J_DIVISAS 
	FOREIGN KEY (DIVISA_DES_ID) REFERENCES J_DIVISAS (ID)
;

ALTER TABLE J_TRANSACCIONES ADD CONSTRAINT FK_J_TRANSACCIONES_J_PRODUCTOS 
	FOREIGN KEY (PROD1_ID) REFERENCES J_PRODUCTOS (ID)
;

ALTER TABLE J_TRANSACCIONES ADD CONSTRAINT FK_J_TRANSACCIONES_J_PRODUCTOS 
	FOREIGN KEY (PROD2_ID) REFERENCES J_PRODUCTOS (ID)
;

ALTER TABLE J_TRANSACCIONES ADD CONSTRAINT FK_J_TRANSACCIONES_J_TRANSACCIONES 
	FOREIGN KEY (TRASAC_PAR_ID) REFERENCES J_TRANSACCIONES (ID)
;

ALTER TABLE J_USUARIOS_RESPON ADD CONSTRAINT FK_J_USUARIOS_RESPON_J_CLIENTES 
	FOREIGN KEY (USUARIO_ID) REFERENCES J_CLIENTES (ID)
;

ALTER TABLE J_USUARIOS_RESPON ADD CONSTRAINT FK_J_USUARIOS_RESPON_J_RESPON_ROLL 
	FOREIGN KEY (RESPONSA_ID) REFERENCES J_RESPON_ROLL (ID)
;

ALTER TABLE J_VISTAS ADD CONSTRAINT FK_J_VISTAS_J_PANTALLAS_MODULOS 
	FOREIGN KEY (PANTALLA_MODULO_ID) REFERENCES J_PANTALLAS_MODULOS (ID)
;

ALTER TABLE J_VISTAS ADD CONSTRAINT FK_J_VISTAS_J_VISTAS 
	FOREIGN KEY (PAR_ROWID) REFERENCES J_VISTAS (ID)
;
